(venv) cam@cam:~/v2-flw/backend/fl_v5$ python client.py   --ensemble-size 8   --ga-generations 2   --ga-population-size 6   --contract-address 0x47e7A7FAb1aEf8994b9b767E8743239D606a749A   --wallet-address 0x73E50a11335222a8D47b4085D20CD745ea81A5Ad 
/home/cam/v2-flw/backend/venv/lib/python3.8/site-packages/xgboost/core.py:265: FutureWarning: Your system has an old version of glibc (< 2.28). We will stop supporting Linux distros with glibc older than 2.28 after **May 31, 2025**. Please upgrade to a recent Linux distro (with glibc 2.28+) to use future versions of XGBoost.
Note: You have installed the 'manylinux2014' variant of XGBoost. Certain features such as GPU algorithms or federated learning are not available. To use these features, please upgrade to a recent Linux distro with glibc 2.28+, and install the 'manylinux_2_28' variant.
  warnings.warn(
2025-05-14 17:27:09,683 - FL-Client-Ensemble - INFO - Using process-based client ID: client-74936
2025-05-14 17:27:09,704 - federated.ipfs - INFO - Connected to IPFS node version: 0.34.1
2025-05-14 17:27:09,704 - FL-Client-Ensemble - INFO - Initialized IPFS connector: http://127.0.0.1:5001/api/v0
Using Ganache account: 0x1D5102A04086332530dbBf906F6D7290EE9302e6
2025-05-14 17:27:09,820 - FL-Client-Ensemble - ERROR - Failed to initialize blockchain connector: Contract JSON not found at /home/cam/v2-flw/backend/fl_v5/contracts/Federation.json
2025-05-14 17:27:09,820 - FL-Client-Ensemble - WARNING - Continuing without blockchain features
2025-05-14 17:27:09,820 - FL-Client-Ensemble - WARNING - Derived dataset files not found: client-74936_train.txt, client-74936_test.txt
2025-05-14 17:27:09,821 - FL-Client-Ensemble - WARNING - Using default dataset files
2025-05-14 17:27:09,821 - FL-Client-Ensemble - INFO - Using dataset files: data/client-1_train.txt and data/client-1_test.txt
2025-05-14 17:27:10,373 - FL-Client-Ensemble - INFO - Dataset loaded - Features: 33
2025-05-14 17:27:10,373 - FL-Client-Ensemble - INFO - Train samples: 5000, Test samples: 5000
2025-05-14 17:27:10,373 - FL-Client-Ensemble - INFO - Positive class ratio: 9.06%
2025-05-14 17:27:10,375 - FL-Client-Ensemble - INFO - Initialized client-74936 with GA-Stacking pipeline
2025-05-14 17:27:10,375 - FL-Client-Ensemble - INFO - IPFS node: http://127.0.0.1:5001/api/v0
2025-05-14 17:27:10,422 - flwr - DEBUG - Opened insecure gRPC connection (no certificates were passed)
2025-05-14 17:27:10,458 - flwr - DEBUG - ChannelConnectivity.IDLE
2025-05-14 17:27:10,466 - flwr - DEBUG - ChannelConnectivity.READY
INFO :      
2025-05-14 17:27:48,251 - flwr - INFO - 
INFO :      Received: train message e3f1c4b0-1685-4029-bca6-c15ebc15643b
2025-05-14 17:27:48,251 - flwr - INFO - Received: train message e3f1c4b0-1685-4029-bca6-c15ebc15643b
WARNING :   Deprecation Warning: The `client_fn` function must return an instance of `Client`, but an instance of `NumpyClient` was returned. Please use `NumPyClient.to_client()` method to convert it to `Client`.
2025-05-14 17:27:48,252 - flwr - WARNING - Deprecation Warning: The `client_fn` function must return an instance of `Client`, but an instance of `NumpyClient` was returned. Please use `NumPyClient.to_client()` method to convert it to `Client`.
2025-05-14 17:27:48,281 - FL-Client-Ensemble - INFO - Split data: train=4000 samples, val=1000 samples
2025-05-14 17:27:48,281 - FL-Client-Ensemble - INFO - Performing GA-Stacking optimization
Generating meta-features...
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1747243675.465744   74936 fork_posix.cc:75] Other threads are currently calling into gRPC, skipping fork() handlers
I0000 00:00:1747243675.502860   74936 fork_posix.cc:75] Other threads are currently calling into gRPC, skipping fork() handlers


[LightGBM] [Info] Number of positive: 290, number of negative: 2910
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.014960 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8163
[LightGBM] [Info] Number of data points in the train set: 3200, number of used features: 33
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.090625 -> initscore=-2.306027
[LightGBM] [Info] Start training from score -2.306027
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Number of positive: 290, number of negative: 2910
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.047975 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8163
[LightGBM] [Info] Number of data points in the train set: 3200, number of used features: 33
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.090625 -> initscore=-2.306027
[LightGBM] [Info] Start training from score -2.306027
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Number of positive: 290, number of negative: 2910
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.010943 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8163
[LightGBM] [Info] Number of data points in the train set: 3200, number of used features: 33
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.090625 -> initscore=-2.306027
[LightGBM] [Info] Start training from score -2.306027
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Number of positive: 289, number of negative: 2911
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.013337 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8163
[LightGBM] [Info] Number of data points in the train set: 3200, number of used features: 33
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.090313 -> initscore=-2.309825
[LightGBM] [Info] Start training from score -2.309825
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Number of positive: 289, number of negative: 2911
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001022 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8163
[LightGBM] [Info] Number of data points in the train set: 3200, number of used features: 33
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.090313 -> initscore=-2.309825
[LightGBM] [Info] Start training from score -2.309825
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
/home/cam/v2-flw/backend/venv/lib/python3.8/site-packages/xgboost/core.py:158: UserWarning: [17:30:57] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
/home/cam/v2-flw/backend/venv/lib/python3.8/site-packages/xgboost/core.py:158: UserWarning: [17:31:02] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
/home/cam/v2-flw/backend/venv/lib/python3.8/site-packages/xgboost/core.py:158: UserWarning: [17:31:09] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
/home/cam/v2-flw/backend/venv/lib/python3.8/site-packages/xgboost/core.py:158: UserWarning: [17:31:11] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
/home/cam/v2-flw/backend/venv/lib/python3.8/site-packages/xgboost/core.py:158: UserWarning: [17:31:17] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
Training base models...
[LightGBM] [Info] Number of positive: 362, number of negative: 3638
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.008692 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8163
[LightGBM] [Info] Number of data points in the train set: 4000, number of used features: 33
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.090500 -> initscore=-2.307545
[LightGBM] [Info] Start training from score -2.307545
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
/home/cam/v2-flw/backend/venv/lib/python3.8/site-packages/xgboost/core.py:158: UserWarning: [17:32:11] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
Generating validation meta-features...
Running GA optimization...
Gen 1/2 - best auc: 0.9996
Gen 2/2 - best auc: 0.9997
AUC : 0.9997340393379998
F1  : 0.9720670391061453
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       909
           1       0.99      0.96      0.97        91

    accuracy                           0.99      1000
   macro avg       0.99      0.98      0.98      1000
weighted avg       0.99      0.99      0.99      1000

2025-05-14 17:32:15,808 - FL-Client-Ensemble - ERROR - Error in GA-Stacking: name 'roc_auc_score' is not defined
AUC : 0.9439488104784817
F1  : 0.7826086956521738
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      4988
           1       0.82      0.75      0.78        12

    accuracy                           1.00      5000
   macro avg       0.91      0.87      0.89      5000
weighted avg       1.00      1.00      1.00      5000

2025-05-14 17:32:16,009 - FL-Client-Ensemble - ERROR - Failed to save ensemble to IPFS: 'NoneType' object has no attribute 'get'
ERROR :     Client raised an exception.
Traceback (most recent call last):
  File "/home/cam/v2-flw/backend/venv/lib/python3.8/site-packages/flwr/client/app.py", line 526, in start_client_internal
    reply_message = client_app(message=message, context=context)
  File "/home/cam/v2-flw/backend/venv/lib/python3.8/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/cam/v2-flw/backend/venv/lib/python3.8/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/cam/v2-flw/backend/venv/lib/python3.8/site-packages/flwr/client/message_handler/message_handler.py", line 129, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
  File "/home/cam/v2-flw/backend/venv/lib/python3.8/site-packages/flwr/client/client.py", line 255, in maybe_call_fit
    return client.fit(fit_ins)
  File "/home/cam/v2-flw/backend/venv/lib/python3.8/site-packages/flwr/client/numpy_client.py", line 259, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "client.py", line 407, in fit
    metrics["ensemble_size"] = len(self.ensemble_state.get("model_names", [])) if hasattr(self, 'ensemble_state') else 0
AttributeError: 'NoneType' object has no attribute 'get'
2025-05-14 17:32:16,009 - flwr - ERROR - Client raised an exception.
Traceback (most recent call last):
  File "/home/cam/v2-flw/backend/venv/lib/python3.8/site-packages/flwr/client/app.py", line 526, in start_client_internal
    reply_message = client_app(message=message, context=context)
  File "/home/cam/v2-flw/backend/venv/lib/python3.8/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/cam/v2-flw/backend/venv/lib/python3.8/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/cam/v2-flw/backend/venv/lib/python3.8/site-packages/flwr/client/message_handler/message_handler.py", line 129, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
  File "/home/cam/v2-flw/backend/venv/lib/python3.8/site-packages/flwr/client/client.py", line 255, in maybe_call_fit
    return client.fit(fit_ins)
  File "/home/cam/v2-flw/backend/venv/lib/python3.8/site-packages/flwr/client/numpy_client.py", line 259, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "client.py", line 407, in fit
    metrics["ensemble_size"] = len(self.ensemble_state.get("model_names", [])) if hasattr(self, 'ensemble_state') else 0
AttributeError: 'NoneType' object has no attribute 'get'
2025-05-14 17:32:16,140 - flwr - DEBUG - gRPC channel closed
Traceback (most recent call last):
  File "client.py", line 765, in <module>
    start_client(
  File "client.py", line 731, in start_client
    fl.client.start_client(server_address=server_address, client=client)
  File "/home/cam/v2-flw/backend/venv/lib/python3.8/site-packages/flwr/client/app.py", line 175, in start_client
    start_client_internal(
  File "/home/cam/v2-flw/backend/venv/lib/python3.8/site-packages/flwr/client/app.py", line 533, in start_client_internal
    raise ex
  File "/home/cam/v2-flw/backend/venv/lib/python3.8/site-packages/flwr/client/app.py", line 526, in start_client_internal
    reply_message = client_app(message=message, context=context)
  File "/home/cam/v2-flw/backend/venv/lib/python3.8/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/cam/v2-flw/backend/venv/lib/python3.8/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/cam/v2-flw/backend/venv/lib/python3.8/site-packages/flwr/client/message_handler/message_handler.py", line 129, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
  File "/home/cam/v2-flw/backend/venv/lib/python3.8/site-packages/flwr/client/client.py", line 255, in maybe_call_fit
    return client.fit(fit_ins)
  File "/home/cam/v2-flw/backend/venv/lib/python3.8/site-packages/flwr/client/numpy_client.py", line 259, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "client.py", line 407, in fit
    metrics["ensemble_size"] = len(self.ensemble_state.get("model_names", [])) if hasattr(self, 'ensemble_state') else 0
AttributeError: 'NoneType' object has no attribute 'get'